### ISSUE TITLE
Runtime usage with DataSource

### ISSUE THREAD

**Issue by heruan** [liquibase/liquibase-hibernate#177]
I need to provide a database migration module and I cannot use changelog files.

Basically I need to calculate runtime (application startup) the needed changes to a provided _datasource_ for a set of Hibernate entities (also using Envers) which are already discovered by Spring Data, and then apply them to the datasource (and reiterate the process on other datasources).

Ideally I need to do this:

```java
for (DataSource ds : dataSources) {
    ChangeLog changelog = calculateChangelog(ds);
    changelog.execute(ds);
}
```

I think this is pretty much what this library does under the hood, but how can I do this explicitly without involving configuration files or any other information than the `DataSource` instances?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-479) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
It is possible to do it, but would involve using Liquibase core APIs. Maybe you could use something like [Liquibase.generateChangelog](https://github.com/liquibase/liquibase/blob/bb97c1a27c4fe679609f7a3c72f662667c0f39c7/liquibase-standard/src/main/java/liquibase/Liquibase.java#L1398)  , print it to a string and then try to feed it to [Liquibase.update](https://github.com/liquibase/liquibase/blob/bb97c1a27c4fe679609f7a3c72f662667c0f39c7/liquibase-standard/src/main/java/liquibase/Liquibase.java#L328) .As you have it in memory you will need to pass the CHANGELOG_ARG parameter, that requires you to instantiate the changelog from your string generated with generateChangelog.

Anyway, as this is quite old I don't think you may use it anymore... otherwise if you need more details please reopen the ticket and I'll be happy to assist!
