### ISSUE TITLE
Same primaryKeyName for Tables in Table per Class (Union) Inheritance  

### ISSUE THREAD

**Issue by mryf323** [liquibase/liquibase-hibernate#210]
I have implemented a Table per Class inheritance using JPA. There was an abstract class annotated whith Table per Class strategy, and two concete classes derived from that. Liqibase-hibernate correctly generates two tables for those concrete classes. The primary key name generated by liquibase-hibernate is the same for concrete classes. I know that this primary key must be set across tables but in some DBMS s like PostgreSQL it is not possible to set a primary key across tables; in such cases, setting the same primary key name for two tables leads to exceptions. 

### Steps to Reproduce
1. Define an abstract class with Table Per Class strategy. (`AbstractProfileObserver`)
1. Define two concrete classes derived from that. (`AgentProfileObserver` & `GroupProfileObserver`)
1. Run `mvn liquibase:diff ` against an empty database.
1. Look at these two create-table change sets, with the same `primaryKeyName`. 

```
    <changeSet author="mryf (generated)" id="1568036175852-6">
        <createTable tableName="group_profile_observer">
            <column autoIncrement="true" name="id" type="BIGINT">
                <constraints primaryKey="true" primaryKeyName="abstract_profPK"/>
            </column>
            <column name="profile_id" type="BIGINT"/>
            <column name="group" type="BIGINT"/>
        </createTable>
    </changeSet>
    <changeSet author="mryf (generated)" id="1568036175852-3">
        <createTable tableName="agent_profile_observer">
            <column autoIncrement="true" name="id" type="BIGINT">
                <constraints primaryKey="true" primaryKeyName="abstract_profPK"/>
            </column>
            <column name="profile_id" type="BIGINT"/>
            <column name="agent_id" type="BIGINT"/>
        </createTable>
    </changeSet>
```

1. Run `mvn liquibase:update` to see this exception.

```
liquibase.exception.DatabaseException: ERROR: relation "abstract_profPK" already exists [Failed SQL: CREATE TABLE group_profile_observer (id BIGSERIAL NOT NULL, profile_id BIGINT, "group" BIGINT, CONSTRAINT "abstract_profPK" PRIMARY KEY (id))]
```

### Expected  Behaviour
As it is not common to set primary key across tables, and so many DBMS s like PostgreSQL do not support it, it is better to set different `primaryKeyName` s in such cases.

### Actual Behaviour
DBMS screams because of duplicate `primaryKeyName`

### Environment Information
* **Operating System**: Ubuntu 18.04.3 LTS
* **liquibase-maven-plugin Version:** 3.5.5
* **liquibase-hibernate5 Version:** 3.6
* **Database:** PostgreSQL
* **JDK Version:** 1.8.2

### Example Application
https://github.com/mryf323/liquibase-hibernate

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-420) by [Unito](https://www.unito.io)

**Comment by mryf323** [comment]
Excuse me; the right url to example is https://github.com/mryf323/LiquibaseDemo

**Comment by Shuumi** [comment]
Hello,
I am not sure I understand your problem correctly. You say that it is better to use differing primary key constraint names because matching ones are not supported by most databases.
This is true and the exception you are getting makes sense. Did you expect the database to allow you to use the same constraint name? If not, can you please describe the problem again?

**Comment by CalinoviciPaul** [comment]
I had the same issue. If I have entity A and it is inherited by entity B and entity C with the inheritance type of TABLE_PER_CLASS and the @Id column is in entity A and therefore inherited, for the entities B and C will be generated primary keys with the same name

**Comment by rsttst** [comment]
After bumping into the same issue, I think I've made out the cause of this behaviour: 
In `PrimaryKeySnapshotGenerator.java`, `org.hibernate.mapping.PrimaryKey::getName` seems to return the primary key name of the super-class instead of the inheriting class. This way, duplicate PK-constraints are created in the diff-changelog.

I'm not sure why exactly this happens though, since Hibernate itself does this correctly when using the `ddl-auto=create` feature. I would appreciate any insight on this.
