### ISSUE TITLE
Add and drop unique key constraints are added for same key in one-to-many relationship table

### ISSUE THREAD

**Issue by Vikas25** [liquibase/liquibase-hibernate#244]
I've two entities with one-to-many relationship defined as 

```
Entity1{
// Some fields
@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
  @OrderColumn
  private List<Entity2> entity2List;
}

Entity2{
// Some fields
}
```

Their change sets are generated along with a relationship table but when a diffChangeLog is applied it gets generated as follows. 

```
<changeSet author="vikas (generated)" id="123456789-10">
        <addUniqueConstraint columnNames="some_column" constraintName="UK_1" tableName="some_table"/>
    </changeSet>
<changeSet author="vikas (generated)" id="123456789-11">
        <dropUniqueConstraint constraintName="UK_1" tableName="some_table"/>
        <addUniqueConstraint columnNames="some_column" constraintName="UK_1" tableName="some_table"/>
    </changeSet>
```

Please note that the constraintName ("UK_1") is same in both cases. Didn't quite get the reasoning behind adding, dropping and then adding again the constraint with same name. This adds unnecessary entries in changelog file.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-408) by [Unito](https://www.unito.io/learn-more)

**Comment by kai902000** [comment]
Same issue here.  It wasnt fix in 3.9.

This is use to connect to oracle 12c but it keeps regenerating the index key.  
example:
https://github.com/kai902000/LiquibaseSpringboot

**Comment by rethab** [comment]
I'm seeing the same behavior for a composite primary key. When running a diff (with the gradle plugin), I get a notice that the primary key has changed:

```
Changed Primary Key(s): 
     usersPK on HIBERNATE.users(a_id, b_id, c_id)
          columns changed from '[HIBERNATE.users.a_id, HIBERNATE.users.b_id, HIBERNATE.users.c_id]' to '[public.users.c_id, public.users.b_id, public.users.a_id]'
```

I tried two things, but to no avail:
- I tried to specify the schema in the gradle plugin (as described here https://github.com/liquibase/liquibase-gradle-plugin/issues/48) suspecting that the problem was `HIBERNATE` vs. `public`. However liquibase-hibernate seems to have a hard-coded schema name: https://github.com/liquibase/liquibase-hibernate/issues/160 
- I tried to change the order of the columns in the primary keys. I managed to do this by renaming, because they seem to be ordered alphabetically with hibernate: https://stackoverflow.com/a/25912739 

----

I also noticed that when generating an initial changelog (against an empty database), this composite primary key is created by marking the columns as such:
```yaml
- column:
  constraints:
    primaryKey: true
    primaryKeyName: usersPK
```

however the changes that are generated as a result of running `./gradlew diffChangeLog` (against a database that should have all tables etc) first creates a new unique index, then drops the primary key and lastly creates a new primary key. I am not sure if this behavior of separately creating the unique index and primary key is expected though.

**Comment by rethab** [comment]
So right after writing the above comment, I tried one last thing: Update liquibase and liquibase-hibernate to 4.0.0. And this totally solves this issue :tada: 

Not sure if that's a change in liquibase itself or liquibase-hibernate, but what I noticed is that when generating the initial changes (see second part of my comment above), primary keys are no longer created by simply marking the columns as such, but with a separate changeset like so (changed here: https://github.com/liquibase/liquibase/commit/8412fdbce5616dcbbf3caee798ea29fb7f8e18c7):
```yaml
- changeSet:
    changes:
    - addPrimaryKey:
        columnNames: a_id, b_id, c_id
        constraintName: usersPK
        tableName: users
```

And then this also made me realize that I was using liquibase 3.8.1 which is quite old.

**Comment by filipelautert** [comment]
Hi - we have some fixes and workarounds on this answer. Please reopen the issue if it is not fixable by using any of them.
